from __future__ import annotations

import fcntl
import hashlib
import os
import plistlib
import re
import shlex
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator


_LEGACY_STATE_DIRNAME = ".goal"
_LEGACY_CONFIG_FILENAME = "goal.toml"
_LEGACY_REPOSITORY_LOCK_FILENAME = "goal-cli-repository.lock"
_LEGACY_CACHE_DIRNAME = "goal-cli"
_LEGACY_SCHEDULER_PREFIX = "com.goal-cli"
_LEGACY_SYSTEMD_MARKER = "# Generated by goal-cli system heartbeat."
_LEGACY_CONSOLE_COMMAND = "goal-cli"
_LEGACY_MODULE_NAMES = frozenset({"goal_cli", "goal_cli.cli"})
_GEZHI_CONSOLE_COMMAND = "gezhi"
_GEZHI_MODULE_NAMES = frozenset({"gezhi", "gezhi.cli"})
_PYTHON_FLAG_OPTIONS = frozenset({"-B", "-d", "-E", "-I", "-O", "-OO", "-P", "-q", "-R", "-s", "-S", "-u", "-v"})
_PYTHON_VALUE_OPTIONS = frozenset({"-W", "-X"})


class LegacyMigrationRequired(RuntimeError):
    """Raised when continuing could split durable state or concurrent ownership."""


def ensure_init_target_is_migrated(config_path: Path) -> None:
    """Refuse to initialize GEZHI beside an earlier config or state root."""

    ensure_config_identity_is_migrated(config_path)
    target_dir = config_path.resolve(strict=False).parent
    legacy_state = target_dir / _LEGACY_STATE_DIRNAME
    conflicts = tuple(path for path in (legacy_state,) if _path_exists(path))
    if conflicts:
        paths = ", ".join(str(path) for path in conflicts)
        raise LegacyMigrationRequired(
            "legacy config or runtime state requires manual migration before GEZHI initialization; "
            f"rename the config and state root first: {paths}"
        )


def ensure_config_identity_is_migrated(config_path: Path) -> None:
    """Reject the earlier canonical config identity even with new state paths."""

    if config_path.name == _LEGACY_CONFIG_FILENAME:
        raise LegacyMigrationRequired(
            "legacy config filename is no longer supported; rename it to gezhi.toml before loading GEZHI: "
            f"{config_path}"
        )
    legacy_config = config_path.parent / _LEGACY_CONFIG_FILENAME
    if _path_exists(legacy_config):
        raise LegacyMigrationRequired(
            "legacy config remains beside the GEZHI config; migrate or remove it before continuing: "
            f"{legacy_config}"
        )


def ensure_legacy_state_is_migrated(root: Path, state_dir: Path, runs_dir: Path) -> None:
    """Reject legacy state on disk and configurations that still target it."""

    legacy_state_path = root / _LEGACY_STATE_DIRNAME
    legacy_state_dir = legacy_state_path.resolve(strict=False)
    conflicts: list[Path] = []
    if _path_exists(legacy_state_path):
        conflicts.append(legacy_state_path)
    for configured_path in (state_dir, runs_dir):
        resolved = configured_path.resolve(strict=False)
        if _inside(legacy_state_dir, resolved) and resolved not in conflicts:
            conflicts.append(resolved)
    if conflicts:
        paths = ", ".join(str(path) for path in conflicts)
        raise LegacyMigrationRequired(
            "legacy runtime state must be moved manually before GEZHI can load or run; "
            f"the earlier state root is not supported in place: {paths}"
        )


def ensure_no_legacy_heartbeat(root: Path, current_state_dir: Path) -> None:
    """Fail closed when another state root still owns a heartbeat lock."""

    legacy_state_dir = (root / _LEGACY_STATE_DIRNAME).resolve(strict=False)
    if current_state_dir.resolve(strict=False) == legacy_state_dir:
        return
    legacy_lock = legacy_state_dir / ".heartbeat.lock"
    if legacy_lock.exists():
        raise LegacyMigrationRequired(
            "legacy heartbeat state is still present; stop the earlier runtime and migrate or remove "
            f"the stale lock manually before running GEZHI: {legacy_lock}"
        )


def ensure_runtime_is_migrated(
    root: Path,
    state_dir: Path,
    runs_dir: Path,
    goal_name: str,
) -> None:
    """Fail closed before a run when state, locks, or schedulers remain legacy-owned."""

    ensure_legacy_state_is_migrated(root, state_dir, runs_dir)
    ensure_no_legacy_heartbeat(root, state_dir)
    scheduler_conflicts = (
        *legacy_scheduler_artifacts("launchd", goal_name, root),
        *legacy_scheduler_artifacts("systemd-user", goal_name, root),
    )
    if scheduler_conflicts:
        paths = ", ".join(str(path) for path in scheduler_conflicts)
        raise LegacyMigrationRequired(
            "legacy scheduler artifacts require manual uninstall before GEZHI can run: "
            f"{paths}"
        )


def legacy_scheduler_artifacts(manager: str, goal_name: str, root: Path) -> tuple[Path, ...]:
    """Return scheduler files owned by the earlier runtime identity."""

    label = _legacy_scheduler_label(goal_name, root)
    matches: set[Path] = set()
    if manager == "launchd":
        agent_dir = Path.home() / "Library" / "LaunchAgents"
        default_path = agent_dir / f"{label}.plist"
        if _path_exists(default_path):
            matches.add(default_path)
        for path in agent_dir.glob("*.plist") if agent_dir.is_dir() else ():
            if _is_legacy_launchd_artifact(path, root):
                matches.add(path)
    elif manager == "systemd-user":
        config_home = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")).expanduser()
        unit_dir = config_home / "systemd" / "user"
        for suffix in ("service", "timer"):
            default_path = unit_dir / f"{label}.{suffix}"
            if _path_exists(default_path):
                matches.add(default_path)
        for path in unit_dir.glob("*.service") if unit_dir.is_dir() else ():
            if _is_legacy_systemd_service(path, root):
                matches.add(path)
                timer_path = path.with_suffix(".timer")
                if _path_exists(timer_path):
                    matches.add(timer_path)
    return tuple(sorted(matches, key=str))


def is_legacy_runtime_command(command: str) -> bool:
    return _is_runtime_command(command, _LEGACY_CONSOLE_COMMAND, _LEGACY_MODULE_NAMES)


def is_gezhi_runtime_command(command: str) -> bool:
    return _is_runtime_command(command, _GEZHI_CONSOLE_COMMAND, _GEZHI_MODULE_NAMES)


def is_codex_exec_command(command: str) -> bool:
    invocation = _command_invocation(command)
    executable, arguments = _unwrap_script_runtime(invocation)
    return executable == "codex" and bool(arguments) and arguments[0] == "exec"


def is_claude_print_command(command: str) -> bool:
    invocation = _command_invocation(command)
    executable, arguments = _unwrap_script_runtime(invocation)
    return executable == "claude" and "--print" in arguments


def command_argument_tokens(command: str) -> tuple[str, ...]:
    """Return operational arguments without env, interpreter, or entrypoint paths."""

    try:
        tokens = shlex.split(command)
    except ValueError:
        return ()
    invocation = _unwrap_env_command(tokens)
    if not invocation:
        return ()
    arguments = invocation[1:]
    executable = Path(invocation[0]).name
    if re.fullmatch(r"(?:python(?:\d+(?:\.\d+)*)?|pypy\d*)", executable) is None:
        return tuple(arguments)
    entrypoint = _python_entrypoint(arguments)
    if not entrypoint:
        return ()
    if entrypoint[0] == "-m":
        return tuple(entrypoint[2:])
    return tuple(entrypoint[1:])


def _is_runtime_command(command: str, console_command: str, module_names: frozenset[str]) -> bool:
    invocation = _command_invocation(command)
    if not invocation:
        return False
    executable = Path(invocation[0]).name
    if executable == console_command:
        return True
    if re.fullmatch(r"(?:python(?:\d+(?:\.\d+)*)?|pypy\d*)", executable) is None:
        return False
    entrypoint = _python_entrypoint(invocation[1:])
    if not entrypoint:
        return False
    if entrypoint[0] == "-m":
        return len(entrypoint) >= 2 and entrypoint[1] in module_names
    return Path(entrypoint[0]).name == console_command


@contextmanager
def guard_legacy_repository_lock(canonical_root: Path) -> Iterator[None]:
    """Hold the earlier repository lock so old and new runtimes cannot commit concurrently."""

    lock_path = _legacy_repository_lock_path(canonical_root)
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    with lock_path.open("a+b") as lock_file:
        try:
            fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError as exc:
            raise LegacyMigrationRequired(
                f"legacy repository lock is active; refusing concurrent GEZHI transaction: {lock_path}"
            ) from exc
        try:
            yield
        finally:
            fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)


def _legacy_scheduler_label(goal_name: str, root: Path) -> str:
    name = re.sub(r"[^A-Za-z0-9_.-]+", "-", goal_name).strip("-._") or "goal"
    digest = hashlib.sha1(str(root.resolve()).encode("utf-8")).hexdigest()[:10]
    return f"{_LEGACY_SCHEDULER_PREFIX}.{name}.{digest}"


def _legacy_repository_lock_path(canonical_root: Path) -> Path:
    canonical_root = canonical_root.resolve(strict=False)
    dot_git = canonical_root / ".git"
    if dot_git.is_dir():
        return dot_git / _LEGACY_REPOSITORY_LOCK_FILENAME
    digest = hashlib.sha256(str(canonical_root).encode("utf-8")).hexdigest()
    return Path.home() / ".cache" / _LEGACY_CACHE_DIRNAME / "repository-locks" / f"{digest}.lock"


def _is_legacy_launchd_artifact(path: Path, root: Path) -> bool:
    try:
        parsed = plistlib.loads(path.read_bytes())
    except (OSError, plistlib.InvalidFileException, ValueError):
        return False
    if not isinstance(parsed, dict):
        return False
    working_directory = parsed.get("WorkingDirectory")
    arguments = parsed.get("ProgramArguments")
    return (
        isinstance(working_directory, str)
        and Path(working_directory).resolve(strict=False) == root.resolve(strict=False)
        and isinstance(arguments, list)
        and all(isinstance(item, str) for item in arguments)
        and _has_legacy_module_invocation(arguments)
    )


def _is_legacy_systemd_service(path: Path, root: Path) -> bool:
    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False
    encoded_root = str(root.resolve(strict=False)).replace("%", "%%")
    working_directory = f"WorkingDirectory={encoded_root}"
    return (
        _LEGACY_SYSTEMD_MARKER in content
        and working_directory in content.splitlines()
        and any(module_name in content for module_name in _LEGACY_MODULE_NAMES)
    )


def _has_legacy_module_invocation(arguments: list[str]) -> bool:
    return any(
        token == "-m" and arguments[index + 1] in _LEGACY_MODULE_NAMES
        for index, token in enumerate(arguments[:-1])
    )


def _unwrap_env_command(tokens: list[str]) -> list[str]:
    if not tokens or Path(tokens[0]).name != "env":
        return tokens
    index = 1
    while index < len(tokens) and (tokens[index].startswith("-") or "=" in tokens[index]):
        index += 1
    return tokens[index:]


def _command_invocation(command: str) -> list[str]:
    try:
        tokens = shlex.split(command)
    except ValueError:
        return []
    return _unwrap_env_command(tokens)


def _unwrap_script_runtime(invocation: list[str]) -> tuple[str, list[str]]:
    if not invocation:
        return "", []
    executable = Path(invocation[0]).name
    arguments = invocation[1:]
    if executable in {"node", "nodejs", "bun", "deno"} and arguments:
        executable = Path(arguments[0]).stem
        arguments = arguments[1:]
    return executable, arguments


def _python_entrypoint(arguments: list[str]) -> list[str]:
    index = 0
    while index < len(arguments):
        option = arguments[index]
        if option in _PYTHON_FLAG_OPTIONS:
            index += 1
            continue
        if option in _PYTHON_VALUE_OPTIONS:
            index += 2
            continue
        break
    return arguments[index:]


def _path_exists(path: Path) -> bool:
    return path.exists() or path.is_symlink()


def _inside(parent: Path, candidate: Path) -> bool:
    try:
        candidate.relative_to(parent)
    except ValueError:
        return False
    return True
